/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SearchFunctionality;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import lab9.FriendManagment;
import lab9.User;

/**
 *
 * @author mazen
 */
public class UserSearchFriendFrame extends javax.swing.JFrame {

    private ArrayList<User> users;
    private final FriendManagment friendManager;
    private final String currentname;

    /**
     * Creates new form UserSearchFriend
     *
     * @param currentname
     */
    public UserSearchFriendFrame(User currentname) {
        this.currentname = currentname.getUsername();
        // Initialize friendManager
        this.friendManager = FriendManagment.getInstance(currentname.getUserId());
        setTitle("User Search - " + currentname.getUsername()); // Set the title of the frame
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    public void loadAllUsers() {
        DefaultListModel<String> listModel = new DefaultListModel<>();
        for (User user : users) {
            listModel.addElement(user.getUsername());
        }
        FriendjList1.setModel(listModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Name = new javax.swing.JLabel();
        UserNameText = new javax.swing.JTextField();
        Search = new javax.swing.JButton();
        AddFriend = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        FriendjList1 = new javax.swing.JList<>();
        RemoveFriend = new javax.swing.JButton();
        BlockUser = new javax.swing.JButton();
        ViewProfile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Name.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Name.setText("Name:");

        UserNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameTextActionPerformed(evt);
            }
        });

        Search.setBackground(new java.awt.Color(204, 204, 255));
        Search.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        AddFriend.setBackground(new java.awt.Color(204, 204, 255));
        AddFriend.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AddFriend.setText("Add Friend");
        AddFriend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFriendActionPerformed(evt);
            }
        });

        FriendjList1.setBackground(new java.awt.Color(60, 63, 65));
        FriendjList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(FriendjList1);

        RemoveFriend.setBackground(new java.awt.Color(204, 204, 255));
        RemoveFriend.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RemoveFriend.setText("Remove Friend");
        RemoveFriend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveFriendActionPerformed(evt);
            }
        });

        BlockUser.setBackground(new java.awt.Color(204, 204, 255));
        BlockUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BlockUser.setText("Block User");
        BlockUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlockUserActionPerformed(evt);
            }
        });

        ViewProfile.setBackground(new java.awt.Color(204, 204, 255));
        ViewProfile.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ViewProfile.setText("View Profile");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UserNameText))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddFriend, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RemoveFriend)
                            .addComponent(BlockUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(ViewProfile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(Search))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Name)
                        .addComponent(UserNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(AddFriend, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RemoveFriend, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BlockUser)
                        .addGap(18, 18, 18)
                        .addComponent(ViewProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameTextActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        users = UserSearch.search(UserNameText.getText(), currentname);
        loadAllUsers();
    }//GEN-LAST:event_SearchActionPerformed

    private void AddFriendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFriendActionPerformed
        int index = FriendjList1.getSelectedIndex();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Choose user");
        } else {
            User u = users.get(index);
            friendManager.sendRequest(u.getUserId());
            JOptionPane.showMessageDialog(this, "Add friend successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_AddFriendActionPerformed

    private void BlockUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlockUserActionPerformed
        int index = FriendjList1.getSelectedIndex();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Choose user");
        } else {
            User u = users.get(index);
            friendManager.blockUser(u.getUserId());
            JOptionPane.showMessageDialog(this, "Friend Block successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_BlockUserActionPerformed

    private void RemoveFriendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveFriendActionPerformed
        int index = FriendjList1.getSelectedIndex();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Choose user");
        } else {
            User u = users.get(index);
            friendManager.removeFriend(u.getUserId());
            JOptionPane.showMessageDialog(this, "Friend removed successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_RemoveFriendActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddFriend;
    private javax.swing.JButton BlockUser;
    private javax.swing.JList<String> FriendjList1;
    private javax.swing.JLabel Name;
    private javax.swing.JButton RemoveFriend;
    private javax.swing.JButton Search;
    private javax.swing.JTextField UserNameText;
    private javax.swing.JButton ViewProfile;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
