/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SearchFunctionality;

import contentcreation.Posts;
import java.awt.BorderLayout;
import java.util.List;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import lab9.ContentDatabase;

/**
 *
 * @author mazen
 */
public class ViewGroupFrame extends javax.swing.JFrame {

    private JTable postsTable;
    private JScrollPane scrollPane;

    /**
     * Creates new form ViewGroupFrame
     *
     * @param groupId
     */
    public ViewGroupFrame(String groupId) {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Group Posts");

        // Set layout
        setLayout(new BorderLayout());

        // Create table to display posts
        postsTable = new JTable();
        scrollPane = new JScrollPane(postsTable);

        // Add scroll pane to the frame
        add(scrollPane, BorderLayout.CENTER);

        pack();
        loadGroupPosts(groupId);
    }

    private void loadGroupPosts(String groupId) {
        // Get group posts from the database
        List<Posts> groupPosts = ContentDatabase.getInstance().getGroupPosts(groupId);

        // Define column names
        String[] columnNames = {"Author ID", "Content", "Timestamp"};

        // Populate table data
        String[][] data = new String[groupPosts.size()][3];
        for (int i = 0; i < groupPosts.size(); i++) {
            Posts post = groupPosts.get(i);
            data[i][0] = post.getAuthorId();
            data[i][1] = post.getContent().toString(); // Assuming a `getContent` method exists
            data[i][2] = post.getCreatedtime().toString(); // Assuming a `getTimestamp` method exists
        }

        // Set table model
        postsTable.setModel(new javax.swing.table.DefaultTableModel(data, columnNames));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
