/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package contentcreation;
import java.awt.*;
import java.util.List;
import java.util.ArrayList;
import javax.swing.*;
import lab9.*;
/**
 *
 * @author mazen
 */
public class NewsFeedFriendStatus extends javax.swing.JPanel {
 FriendDatabase friendDatabase=FriendDatabase.getInstance();
    /**
     * Creates new form NewsFeedFriendStatus
     * @param user
     */
    public NewsFeedFriendStatus(User user) {
        initComponents();
        setLayout(new GridLayout(0,2));
        List<User>friends=friendDatabase.getFriendsUsers(user.getUserId());
        ArrayList<String> friendsStatus = new ArrayList<>();
        for (User friend:friends) {
            friendsStatus.add(friend.getUsername()+" | "+friend.getStatus());
        }
        String[] statusArray = friendsStatus.toArray(String[]::new);
       //String[]friends={"ahmed  online","mohamed  offline","belal  offline","bro  offline"};
        JList<String>friendsList=new JList<>(statusArray);
        add(new JScrollPane(friendsList));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 164, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
