/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package contentcreation;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import lab9.*;
/**
 *
 * @author mazen
 */
public class NewsFeedFriendSuggestion extends javax.swing.JPanel {
UserDatabase userDatabase=UserDatabase.getInstance();
private final String friendId;
private final FriendManagment friendManager;
    /**
     * Creates new form NewsFeedFriendSuggestion
     * @param friendManager
     * @param friendId
     */
    public NewsFeedFriendSuggestion(FriendManagment friendManager,String friendId) {
       this.friendManager=friendManager;
        this.friendId=friendId;
        initComponents();
        pfp.setHorizontalAlignment(JLabel.CENTER);
        pfp.setVerticalAlignment(JLabel.CENTER);
        ImageIcon pfpIcon = new ImageIcon(userDatabase.getRecord(friendId).getProfile().getPfpPath());
        //ImageIcon pfpIcon=new ImageIcon("src/resources/default-avatar.png");
        Image image = pfpIcon.getImage().getScaledInstance(80,80, Image.SCALE_SMOOTH);
        pfpIcon = new ImageIcon(image);
        pfp.setIcon(pfpIcon);
        username.setText(userDatabase.getRecord(friendId).getUsername());
        //username.setText("bruhh");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pfp = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        sendRequest = new javax.swing.JButton();

        username.setText("Friend Suggestion Name");

        sendRequest.setText("Send Request");
        sendRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendRequestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pfp, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(username)
                    .addComponent(sendRequest))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pfp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(username)
                .addGap(18, 18, 18)
                .addComponent(sendRequest)
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sendRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendRequestActionPerformed
    friendManager.sendRequest(friendId);
    }//GEN-LAST:event_sendRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel pfp;
    private javax.swing.JButton sendRequest;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
