/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package contentcreation;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import lab9.*;

/**
 *
 * @author bassam
 */
public class ProfileRequests extends javax.swing.JPanel {
UserDatabase userDatabase=UserDatabase.getInstance();
private FriendManagment friendManager;
private String userId;
FriendDatabase friendDatabase=FriendDatabase.getInstance();
private String requestId;
    /**
     * Creates new form ProfileRequests
     * @param friendManager
     * @param requestId
     */
    public ProfileRequests(FriendManagment friendManager,String requestId) {
        initComponents();
        this.friendManager=friendManager;
        this.requestId=requestId;
        userId=friendManager.getUserId();
        pfp.setHorizontalAlignment(JLabel.CENTER);
        pfp.setVerticalAlignment(JLabel.CENTER);
        ImageIcon pfpIcon = new ImageIcon(userDatabase.getRecord(requestId).getProfile().getPfpPath());
        Image image = pfpIcon.getImage().getScaledInstance(80,80, Image.SCALE_SMOOTH);
        pfpIcon = new ImageIcon(image);
        pfp.setIcon(pfpIcon);
        username.setText(userDatabase.getRecord(requestId).getUsername());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pfp = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        Accept = new javax.swing.JButton();
        decline = new javax.swing.JButton();

        pfp.setText("jLabel1");

        username.setText("username");

        Accept.setText("Accept");
        Accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptActionPerformed(evt);
            }
        });

        decline.setText("Decline");
        decline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                declineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pfp, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Accept)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(decline))
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Accept)
                    .addComponent(decline)
                    .addComponent(pfp, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptActionPerformed
       friendManager.acceptRequest(friendDatabase.getRecord(requestId+"-"+userId));
    }//GEN-LAST:event_AcceptActionPerformed

    private void declineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_declineActionPerformed
      friendManager.declineRequest(friendDatabase.getRecord(requestId+"-"+userId));
    }//GEN-LAST:event_declineActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Accept;
    private javax.swing.JButton decline;
    private javax.swing.JLabel pfp;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
