/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FrontEnd;

import java.awt.GridLayout;
import java.util.List;
import lab9.FriendDatabase;
import lab9.FriendRequest;
import lab9.User;

/**
 *
 * @author Rana
 */
public class FriendRequestsPanel extends javax.swing.JPanel {
 FriendDatabase friendDatabase=FriendDatabase.getInstance();

    /**
     * Creates new form FriendRequestsPanel
     */
    public FriendRequestsPanel(User user) {
        initComponents();
        setLayout(new GridLayout(0,2));
        List<FriendRequest> requests=friendDatabase.getRecievedRequests(user.getUserId());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
