/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FrontEnd;

import lab9.GroupManagement;
import lab9.User;
import lab9.UserDatabase;

/**
 *
 * @author Zeina
 */
public class ManageMembers extends javax.swing.JPanel {

    private GroupManagement grpmanage;
    UserDatabase userDatabase = UserDatabase.getInstance();
    private String userId;
    private String adminId;

    /**
     * Creates new form ManageMembers
     */
    public ManageMembers(GroupManagement grpmanage, String userId, String adminId) {
        initComponents();
        this.grpmanage = grpmanage;
        this.userId = userId;
        this.adminId = adminId;
        memberUsername.setText(userDatabase.getRecord(userId).getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        memberUsername = new javax.swing.JLabel();
        promote = new javax.swing.JButton();
        demote = new javax.swing.JButton();
        remove = new javax.swing.JButton();

        memberUsername.setText("jLabel1");

        promote.setText("Promote Member");
        promote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promoteActionPerformed(evt);
            }
        });

        demote.setText("Demote Member");
        demote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                demoteActionPerformed(evt);
            }
        });

        remove.setText("Remove Member");
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(memberUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(remove)
                    .addComponent(demote)
                    .addComponent(promote))
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(promote)
                        .addGap(11, 11, 11)
                        .addComponent(memberUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(demote)))
                .addGap(18, 18, 18)
                .addComponent(remove)
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        grpmanage.removeMember(adminId, userId);
    }//GEN-LAST:event_removeActionPerformed

    private void promoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promoteActionPerformed
        grpmanage.promoteToAdmin(adminId, userId);
    }//GEN-LAST:event_promoteActionPerformed

    private void demoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_demoteActionPerformed
        grpmanage.demoteAdmin(adminId, userId);
    }//GEN-LAST:event_demoteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton demote;
    private javax.swing.JLabel memberUsername;
    private javax.swing.JButton promote;
    private javax.swing.JButton remove;
    // End of variables declaration//GEN-END:variables
}
