/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FrontEnd;

import SearchFunctionality.ViewGroupFrame;
import lab9.Group;
import lab9.NotificationDatabase;
import lab9.User;

/**
 *
 * @author Zeina
 */
public class NewGroupPostPanel extends javax.swing.JPanel {
NotificationDatabase notificationDatabase = NotificationDatabase.getInstance();
    private String notificationId;
    private Group group;
    private User user;
    /**
     * Creates new form NewGroupPostPanel
     */
    public NewGroupPostPanel(String notificationId, Group group, User user) {
        initComponents();
        this.notificationId=notificationId;
        this.group=group;
        this.user=user;
        notificationMessage.setText(notificationDatabase.getRecord(notificationId).toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        notificationMessage = new javax.swing.JLabel();
        viewGroup = new javax.swing.JButton();

        notificationMessage.setText("jLabel1");

        viewGroup.setText("View Group");
        viewGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewGroupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(notificationMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(notificationMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(viewGroup))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewGroupActionPerformed
       ViewGroupFrame grpFrame=new ViewGroupFrame(group, user);
       grpFrame.setVisible(true);
    }//GEN-LAST:event_viewGroupActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel notificationMessage;
    private javax.swing.JButton viewGroup;
    // End of variables declaration//GEN-END:variables
}
