/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FrontEnd;

import java.awt.Image;
import javax.swing.ImageIcon;
import lab9.FriendDatabase;
import lab9.FriendManagment;
import lab9.UserDatabase;

/**
 *
 * @author Zeina
 */
public class ProfileFriendList extends javax.swing.JPanel {

    UserDatabase userDatabase = UserDatabase.getInstance();
    FriendDatabase friendDatabase = FriendDatabase.getInstance();
    private final String friendId;
    private final FriendManagment friendManager;

    /**
     * Creates new form ProfileFriendList
     */
    public ProfileFriendList(FriendManagment friendManager, String friendId) {
        initComponents();
        this.friendManager = friendManager;
        this.friendId = friendId;
        ImageIcon pfpIcon = new ImageIcon(userDatabase.getRecord(friendId).getProfile().getPfpPath());
        Image image = pfpIcon.getImage().getScaledInstance(80,80, Image.SCALE_SMOOTH);
        pfpIcon = new ImageIcon(image);
        pfp.setIcon(pfpIcon);
        String friendStatus="userDatabase.getRecord(friendId).getUsername()+userDatabase.getRecord(friendId).getStatus()";
        friends.setText(friendId);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pfp = new javax.swing.JLabel();
        friends = new javax.swing.JLabel();
        block = new javax.swing.JButton();
        remove = new javax.swing.JButton();

        pfp.setText("jLabel1");

        friends.setText("jLabel2");

        block.setText("Block");
        block.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blockActionPerformed(evt);
            }
        });

        remove.setText("Remove");
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pfp, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(friends, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(block)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(remove)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pfp, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(friends)
                    .addComponent(block)
                    .addComponent(remove))
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void blockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blockActionPerformed
        friendManager.blockUser(friendId);
    }//GEN-LAST:event_blockActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        friendManager.removeFriend(friendId);
    }//GEN-LAST:event_removeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton block;
    private javax.swing.JLabel friends;
    private javax.swing.JLabel pfp;
    private javax.swing.JButton remove;
    // End of variables declaration//GEN-END:variables
}
